name: disret
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - comm=0.2.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.0
  - ipython=8.20.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - ld_impl_linux-64=2.38
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - llvm-openmp=14.0.6
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.9
  - networkx=3.1
  - openssl=3.2.0
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.7
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.11.7
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchtriton=2.1.0
  - tornado=6.3.3
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - attrs==23.2.0
      - beir==2.0.0
      - blessed==1.20.0
      - bpython==0.24
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - curtsies==0.4.2
      - cwcwidth==0.1.9
      - cycler==0.12.1
      - datasets==2.16.1
      - dill==0.3.7
      - elasticsearch==7.9.1
      - faiss-cpu==1.7.4
      - fonttools==4.47.2
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - greenlet==3.0.3
      - huggingface-hub==0.20.2
      - idna==3.6
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - multidict==6.0.5
      - multiprocess==0.70.15
      - nltk==3.8.1
      - numpy==1.26.3
      - pandas==2.1.4
      - pillow==10.2.0
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pyparsing==3.1.1
      - pytrec-eval==0.5
      - pytz==2023.3.post1
      - pyxdg==0.28
      - regex==2023.12.25
      - requests==2.31.0
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - threadpoolctl==3.2.0
      - tokenizers==0.15.0
      - torchvision==0.16.2
      - tqdm==4.66.1
      - transformers==4.36.2
      - tzdata==2023.4
      - urllib3==2.1.0
      - xxhash==3.4.1
      - yarl==1.9.4
