name: cis630
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.8.16
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==22.2.0
      - beir==1.0.1
      - blessed==1.20.0
      - bpython==0.24
      - charset-normalizer==3.1.0
      - click==8.1.3
      - contourpy==1.0.7
      - curtsies==0.4.1
      - cwcwidth==0.1.8
      - cycler==0.11.0
      - datasets==2.10.1
      - dill==0.3.6
      - docopt==0.6.2
      - elasticsearch==7.9.1
      - faiss-cpu==1.7.3
      - filelock==3.9.0
      - fonttools==4.39.0
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - greenlet==2.0.2
      - huggingface-hub==0.12.1
      - idna==3.4
      - importlib-resources==5.12.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - matplotlib==3.7.1
      - multidict==6.0.4
      - multiprocess==0.70.14
      - nltk==3.8.1
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - packaging==23.0
      - pandas==1.5.3
      - pillow==9.4.0
      - pipreqs==0.4.11
      - pyarrow==11.0.0
      - pygments==2.14.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytrec-eval==0.5
      - pytz==2022.7.1
      - pyxdg==0.28
      - pyyaml==6.0
      - regex==2022.10.31
      - requests==2.28.2
      - responses==0.18.0
      - scikit-learn==1.2.1
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.97
      - six==1.16.0
      - threadpoolctl==3.1.0
      - tokenizers==0.13.2
      - torch==1.13.1
      - torchvision==0.14.1
      - tqdm==4.65.0
      - transformers==4.26.1
      - typing-extensions==4.5.0
      - urllib3==1.26.14
      - wcwidth==0.2.6
      - xxhash==3.2.0
      - yarg==0.1.9
      - yarl==1.8.2
      - zipp==3.15.0
